# Generated by Django 6.0.6 on 2026-06-28 18:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_alter_category_slug_and_more'),
        ('products', '0002_remove_product_uniq_product_sku_per_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityAttribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'socket', 'form_factor', 'max_ram_speed_mhz'.", max_length=64, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('data_type', models.CharField(choices=[('STRING', 'String'), ('INTEGER', 'Integer'), ('JSON_ARRAY', 'JSON array')], default='STRING', max_length=16, verbose_name='data type')),
            ],
            options={
                'verbose_name': 'Compatibility attribute',
                'verbose_name_plural': 'Compatibility attributes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PCBuild',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='My Build', max_length=120, verbose_name='name')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
                ('share_token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='share token')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Sum of selected products' effective prices.", max_digits=12, verbose_name='total price')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETE', 'Complete')], db_index=True, default='DRAFT', max_length=16, verbose_name='status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pc_builds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PC build',
                'verbose_name_plural': 'PC builds',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='PCBuildItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('CPU', 'CPU'), ('MOBO', 'Motherboard'), ('RAM_1', 'Memory slot 1'), ('RAM_2', 'Memory slot 2'), ('GPU', 'Graphics card'), ('PSU', 'Power supply'), ('CASE', 'PC case'), ('COOLER', 'CPU cooler'), ('SSD_1', 'Storage SSD slot 1'), ('SSD_2', 'Storage SSD slot 2'), ('HDD', 'Storage HDD')], max_length=16, verbose_name='slot')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compatibility.pcbuild')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='build_items', to='products.product')),
            ],
            options={
                'verbose_name': 'PC build item',
                'verbose_name_plural': 'PC build items',
                'ordering': ('slot',),
            },
        ),
        migrations.CreateModel(
            name='CompatibilityRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rule_name', models.CharField(help_text="Unique identifier, e.g. 'CPU_MOBO_SOCKET'.", max_length=80, unique=True, verbose_name='rule name')),
                ('rule_type', models.CharField(choices=[('MATCH', 'Match (string equality)'), ('MEMBER_OF', 'Member of (value in JSON array)'), ('RANGE_MAX', 'Range max (a <= b)'), ('POWER_CHECK', 'Power check (sum TDP <= PSU * 0.80)')], max_length=16, verbose_name='rule type')),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], default='ERROR', max_length=16, verbose_name='severity')),
                ('description', models.TextField(help_text='Human-readable explanation shown in the UI accordion.', verbose_name='description')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is active')),
                ('attribute_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_as_a', to='compatibility.compatibilityattribute', verbose_name='attribute A')),
                ('attribute_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rules_as_b', to='compatibility.compatibilityattribute', verbose_name='attribute B')),
                ('category_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_a', to='categories.category', verbose_name='category A')),
                ('category_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules_as_b', to='categories.category', verbose_name='category B')),
            ],
            options={
                'verbose_name': 'Compatibility rule',
                'verbose_name_plural': 'Compatibility rules',
                'ordering': ('rule_name',),
                'indexes': [models.Index(fields=['is_active', 'rule_type'], name='compatibili_is_acti_987f15_idx'), models.Index(fields=['category_a', 'is_active'], name='compatibili_categor_a5e60d_idx'), models.Index(fields=['category_b', 'is_active'], name='compatibili_categor_cd6956_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pcbuild',
            index=models.Index(fields=['user', '-updated_at'], name='compatibili_user_id_371d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='pcbuild',
            index=models.Index(fields=['status'], name='compatibili_status_84b923_idx'),
        ),
        migrations.AddIndex(
            model_name='pcbuilditem',
            index=models.Index(fields=['build', 'slot'], name='compatibili_build_i_bdae1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='pcbuilditem',
            constraint=models.UniqueConstraint(fields=('build', 'slot'), name='uniq_builditem_build_slot'),
        ),
    ]
