# Generated by Django 6.0.6 on 2026-06-27 17:35

import apps.categories.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=apps.categories.models._category_icon_path, verbose_name='icon')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.categories.models._category_image_path, verbose_name='banner image')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('spec_template', models.JSONField(blank=True, default=list, help_text='Per-category spec field definitions (see spec §2.7).', verbose_name='spec template')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='categories.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('display_order', 'name'),
                'indexes': [models.Index(fields=['parent', 'display_order'], name='categories__parent__284249_idx')],
            },
        ),
    ]
