# Generated by Django 6.0.6 on 2026-06-28 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, help_text="Submitted email (lowercased). Always recorded even for non-existent accounts so attackers can't probe via timing.", max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, default='', help_text='Stable code: bad_credentials, account_disabled, account_locked, role_mismatch.', max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Login attempt',
                'verbose_name_plural': 'Login attempts',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['email', '-timestamp'], name='common_logi_email_a41605_idx'), models.Index(fields=['ip_address', '-timestamp'], name='common_logi_ip_addr_b0947e_idx'), models.Index(fields=['success', '-timestamp'], name='common_logi_success_16a676_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text="Stable machine token, e.g. 'user.suspend', 'vendor.approve'.", max_length=80)),
                ('target_type', models.CharField(blank=True, default='', help_text="Lowercase model name, e.g. 'user', 'vendor', 'product'.", max_length=80)),
                ('target_id', models.CharField(blank=True, default='', help_text="String form of the target's PK (UUIDs, ints, slugs all supported).", max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user (usually an admin) who performed the action. Null for system-triggered actions (e.g. auto-lockout).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit log entry',
                'verbose_name_plural': 'Audit log entries',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['action', '-timestamp'], name='common_audi_action_ad6716_idx'), models.Index(fields=['target_type', 'target_id'], name='common_audi_target__65ba7e_idx'), models.Index(fields=['actor', '-timestamp'], name='common_audi_actor_i_38053e_idx')],
            },
        ),
    ]
