# Generated by Django 6.0.6 on 2026-06-28 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_remove_product_uniq_product_sku_per_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Set on create; bumped on dedup hit.')),
                ('session_key', models.CharField(blank=True, default='', help_text='Opaque client-supplied key for anonymous tracking.', max_length=64)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='products.product')),
                ('user', models.ForeignKey(blank=True, db_index=False, help_text='Null for anonymous views.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product view',
                'verbose_name_plural': 'Product views',
                'ordering': ('-viewed_at',),
                'indexes': [models.Index(fields=['product', 'viewed_at'], name='recommendat_product_45d2b3_idx'), models.Index(fields=['user', 'viewed_at'], name='recommendat_user_id_7be016_idx'), models.Index(fields=['session_key', 'viewed_at'], name='recommendat_session_d4e63a_idx')],
            },
        ),
    ]
