# Generated by Django 6.0.6 on 2026-06-29 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(db_index=True, help_text='The exact search string (post-trim, pre-lowercasing for storage).', max_length=255)),
                ('results_count', models.IntegerField(default=0, help_text='Number of products that matched at log time.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the query was made.')),
                ('user', models.ForeignKey(blank=True, help_text='Null for anonymous searches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search log',
                'verbose_name_plural': 'Search logs',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['query', '-timestamp'], name='recommendat_query_51bfee_idx'), models.Index(fields=['user', '-timestamp'], name='recommendat_user_id_af3e79_idx'), models.Index(fields=['results_count', '-timestamp'], name='recommendat_results_127632_idx')],
            },
        ),
    ]
