# Generated by Django 6.0.6 on 2026-06-27 20:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_remove_product_uniq_product_sku_per_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, help_text='PCM-YYYYMMDD-NNNNN -- set by OrderService.generate_order_number', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURN_REQUESTED', 'Return Requested'), ('RETURNED', 'Returned')], db_index=True, default='PENDING_PAYMENT', max_length=32)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=16)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash on Delivery'), ('BKASH', 'bKash'), ('NAGAD', 'Nagad'), ('CARD', 'Card')], default='COD', max_length=16)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_address_snapshot', models.JSONField(default=dict, help_text='Output of ShippingAddress.to_snapshot() at order time.')),
                ('notes', models.TextField(blank=True, default='')),
                ('delivery_partner', models.CharField(blank=True, default='', help_text='Optional FK-friendly string for the courier; left blank for now.', max_length=120)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=120)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('product_slug_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('primary_image_url', models.URLField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Effective price at the moment of order.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_snapshot', models.DecimalField(decimal_places=2, default=0, help_text='Total discount applied at order time (BDT).', max_digits=12)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=20)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='item', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
                ('vendor', models.ForeignKey(help_text='Denormalised from Product.vendor at order time.', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='accounts.vendorprofile')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='Home', help_text="Friendly tag, e.g. 'Home', 'Office'.", max_length=80)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('street_address', models.CharField(help_text='House + road; the primary delivery line.', max_length=255)),
                ('address_line2', models.CharField(blank=True, help_text='Optional secondary line (apartment, floor, etc.).', max_length=255)),
                ('city', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=80)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='Bangladesh', max_length=80)),
                ('is_default', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', related_query_name='shipping_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ('-is_default', '-updated_at'),
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='orders_orde_user_id_0ae59f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_orde_status_079368_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', '-created_at'], name='orders_orde_payment_8bdf8b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['vendor', '-created_at'], name='orders_orde_vendor__888f6d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['vendor', 'item_status'], name='orders_orde_vendor__f6dc2a_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['user', 'is_default'], name='orders_ship_user_id_bcf520_idx'),
        ),
    ]
