# Generated by Django 6.0.6 on 2026-06-28 05:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('return_number', models.CharField(db_index=True, help_text='RET-YYYYMMDD-NNNNN -- set by ReturnService.generate_return_number', max_length=32, unique=True)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('NOT_AS_DESCRIBED', 'Not as described'), ('WRONG_ITEM', 'Wrong item received'), ('DEFECTIVE', 'Defective on arrival'), ('MISSING_PARTS', 'Missing parts or accessories')], db_index=True, default='DAMAGED', max_length=32)),
                ('description', models.TextField(help_text='Free-form customer explanation. Min 20 chars per spec.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SHIPPED_BACK', 'Shipped back'), ('RECEIVED', 'Received by vendor'), ('REFUND_INITIATED', 'Refund initiated'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=32)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Filled when the vendor rejects the request.')),
                ('tracking_number_return', models.CharField(blank=True, default='', help_text="Customer's tracking number for the return shipment.", max_length=120)),
                ('vendor_notes', models.TextField(blank=True, default='')),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_back_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('refund_initiated_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(help_text='The buyer who initiated the return.', on_delete=django.db.models.deletion.PROTECT, related_name='return_requests', related_query_name='return_request', to=settings.AUTH_USER_MODEL)),
                ('order_item', models.OneToOneField(help_text='One return per item -- enforced at the DB level.', on_delete=django.db.models.deletion.CASCADE, related_name='return_request', related_query_name='return_request', to='orders.orderitem')),
            ],
            options={
                'verbose_name': 'Return request',
                'verbose_name_plural': 'Return requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnEvidence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Stored under MEDIA_ROOT/returns/evidence/YYYY/MM/.', upload_to='returns/evidence/%Y/%m/')),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', related_query_name='evidence', to='orders.returnrequest')),
            ],
            options={
                'verbose_name': 'Return evidence',
                'verbose_name_plural': 'Return evidence',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['customer', '-created_at'], name='orders_retu_custome_07ccec_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['status', '-created_at'], name='orders_retu_status_3b5dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order_item'], name='orders_retu_order_i_915661_idx'),
        ),
    ]
