# Generated by Django 6.0.6 on 2026-06-28 05:35

from django.db import migrations, models


def _seed_return_sequence(apps, schema_editor):
    ReturnSequence = apps.get_model("orders", "ReturnSequence")
    ReturnSequence.objects.update_or_create(pk=1, defaults={"last_value": 0})


def _remove_return_sequence(apps, schema_editor):
    # Reverse is a no-op: dropping the table removes the row.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_returnrequest_returnevidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_value', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Return number sequence',
                'verbose_name_plural': 'Return number sequence',
            },
        ),
        migrations.RunPython(_seed_return_sequence, _remove_return_sequence),
    ]

