# Generated by Django 6.0.6 on 2026-06-27 12:31

import apps.accounts.models
import apps.common.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='full name')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.BDPhoneValidator()], verbose_name='phone')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('admin', 'Administrator')], db_index=True, default='customer', max_length=16)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('PREFER_NOT_TO_SAY', 'Prefer not to say')], default='', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profiles/avatars/%Y/%m/', validators=[apps.common.validators.ImageValidator(max_size_mb=5)], verbose_name='avatar')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined',),
            },
            managers=[
                ('objects', apps.accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('loyalty_points', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('newsletter_subscribed', models.BooleanField(default=True)),
                ('preferred_language', models.CharField(blank=True, default='en', max_length=8)),
                ('preferred_currency', models.CharField(blank=True, default='BDT', max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('business_name', models.CharField(max_length=180, verbose_name='business name')),
                ('owner_name', models.CharField(max_length=150, verbose_name='owner name')),
                ('business_type', models.CharField(choices=[('SOLE_PROP', 'Sole proprietorship'), ('PARTNERSHIP', 'Partnership'), ('PVT_LTD', 'Private limited'), ('OTHER', 'Other')], default='SOLE_PROP', max_length=20)),
                ('business_phone', models.CharField(blank=True, max_length=20, validators=[apps.common.validators.BDPhoneValidator()])),
                ('trade_license_number', models.CharField(max_length=80, verbose_name='trade license number')),
                ('trade_license_doc', models.FileField(upload_to=apps.accounts.models._trade_license_path, validators=[apps.common.validators.FileMimeTypeValidator(allowed_mime=['image/', 'application/pdf'], max_size_mb=5)], verbose_name='trade license document')),
                ('nid_number', models.CharField(max_length=40, verbose_name='NID number')),
                ('nid_doc', models.FileField(upload_to=apps.accounts.models._nid_path, validators=[apps.common.validators.FileMimeTypeValidator(allowed_mime=['image/', 'application/pdf'], max_size_mb=5)], verbose_name='NID document')),
                ('business_address', models.JSONField(blank=True, default=dict, help_text='{street, city, district, postal_code}', verbose_name='business address')),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INFO_REQUESTED', 'Additional information requested')], db_index=True, default='PENDING', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('store_name', models.CharField(max_length=120, verbose_name='store name')),
                ('store_slug', models.SlugField(max_length=140, unique=True, verbose_name='store slug')),
                ('store_description', models.TextField(blank=True)),
                ('store_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='store contact email')),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models._store_logo_path, validators=[apps.common.validators.ImageValidator(max_size_mb=5)])),
                ('store_banner', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models._store_banner_path, validators=[apps.common.validators.ImageValidator(max_size_mb=10)])),
                ('vendor_return_policy', models.TextField(blank=True, help_text='Overrides platform default when non-empty (see spec sec 2.8).')),
                ('low_stock_threshold', models.PositiveSmallIntegerField(default=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vendor Profile',
                'verbose_name_plural': 'Vendor Profiles',
                'ordering': ('store_name',),
            },
        ),
    ]
