# Generated by Django 6.0.6 on 2026-06-27 17:35

import apps.brands.models
import apps.common.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.brands.models._brand_logo_path, validators=[apps.common.validators.ImageValidator(max_size_mb=2)], verbose_name='logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=apps.brands.models._brand_banner_path, validators=[apps.common.validators.ImageValidator(max_size_mb=8)], verbose_name='banner')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='is featured')),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_products', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('display_order', 'name'),
            },
        ),
    ]
