# Generated by Django 6.0.6 on 2026-06-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(max_length=140, verbose_name='slug'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('slug',), name='uniq_brand_slug_active'),
        ),
    ]
