# Generated by Django 6.0.6 on 2026-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('brands', '0001_initial'),
        ('categories', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='uniq_product_sku_per_vendor',
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('vendor', 'sku'), name='uniq_product_sku_per_vendor'),
        ),
    ]
